# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-simplesynth

# >> macros
%define _binary_payload w2.xzdio
%define __provides_exclude_from ^%{_datadir}/%{name}/lib/.*\\.so\\>
%define __requires_exclude_from ^%{_datadir}/%{name}/lib/.*\\.so\\>
# << macros

Summary:    An Audio Synth with a simple QML UI
Version:    0.1.4
Release:    1
Group:      Qt/Qt
License:    GPLv3
URL:        http://github.org/poetater/harbour-simplesynth
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-simplesynth.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(sdl2)
BuildRequires:  pkgconfig(SDL2_mixer)
BuildRequires:  desktop-file-utils

%description
A simple audio synth which can be controlled via QUI and by writing generator descriptions.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

#install -D -m 755 --target-directory %{buildroot}%{_datadir}/%{name}/lib/ \
#    /usr/lib/libsynth.so

# >> install post
#install -D -t %{buildroot}/%{_datadir}/%{name}/lib %{_libdir}/libsynth.so.[0-9][0-9]
#install -m 644 -p %{buildroot}/libsynth/libsynth.so.[0-9][0-9] %{buildroot}/usr/share/%{name}/lib/
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
